package com.noty215.notycaption.utils;

import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;

/**
 * Translator for internationalization support
 */
public class Translator {

    private String language;
    private Map<String, String> translations;
    private static final Map<String, Map<String, String>> ALL_TRANSLATIONS = new HashMap<>();

    static {
        // English translations
        Map<String, String> en = new HashMap<>();
        en.put("window_title", "NotyCaption Pro - Professional AI Caption Generator");
        en.put("app_name", "NotyCaption Pro");
        en.put("app_subtitle", "AI-Powered Caption Generator");
        en.put("ready", "Ready");
        en.put("processing", "Processing...");
        en.put("canceled", "Canceled");
        en.put("completed", "Completed");
        en.put("failed", "Failed");
        en.put("edit_captions", "✏️ Edit Captions");
        en.put("save_exit_edit", "💾 Save & Exit Edit");
        en.put("settings", "⚙️ Settings");
        en.put("download_model", "📥 Download Model");
        en.put("login_google", "🔐 Google Login");
        en.put("import_media", "📁 Import Media");
        en.put("browse_output", "📂 Browse Output");
        en.put("enhance_audio", "🎤 Enhance Audio");
        en.put("play_pause", "▶️ Play / ⏸️ Pause");
        en.put("playing", "⏸️ Playing...");
        en.put("paused", "▶️ Play / ⏸️ Pause");
        en.put("generate", "🚀 Generate Captions");
        en.put("cancel", "Cancel Operation");
        en.put("force_cancel", "⚠️ Force Cancel");
        en.put("reopen_notebook", "🔗 Reopen Notebook");
        en.put("copy_url", "📋 Copy URL");
        en.put("workspace", "🎨 Workspace");
        en.put("save_layout", "💾 Save Layout");
        en.put("load_layout", "📂 Load Layout");
        en.put("presets", "🎨 Presets");
        en.put("hardware", "🖥️ Hardware");
        en.put("monitor", "📊 Monitor");
        en.put("performance", "📈 Performance");
        en.put("export", "📤 Export");
        en.put("import", "📥 Import");
        en.put("preview", "👁️ Preview");
        en.put("refresh", "🔄 Refresh");
        en.put("ai_caption_editor", "AI Caption Editor");
        en.put("processing_mode", "Mode:");
        en.put("language", "Language:");
        en.put("words_per_line", "Words/Line:");
        en.put("output_format", "Format:");
        en.put("output_folder", "Output Folder:");
        en.put("status", "Status:");
        en.put("notebook_url", "Notebook URL:");
        en.put("not_available", "Not available");
        en.put("idle", "Idle");
        en.put("speed", "Speed:");
        en.put("eta", "ETA:");
        en.put("downloading", "Downloading...");
        en.put("uploading", "Uploading...");
        en.put("waiting", "Waiting...");
        en.put("colab_link", "Colab Link:");
        en.put("click_to_open", "Click to open in browser");
        en.put("normal_mode", "🖥️ Local");
        en.put("online_mode", "☁️ Online");
        en.put("english_transcribe", "🇺🇸 English");
        en.put("japanese_translate", "🇯🇵 Japanese → English");
        en.put("chinese_transcribe", "🇨🇳 Chinese");
        en.put("french_transcribe", "🇫🇷 French");
        en.put("german_transcribe", "🇩🇪 German");
        en.put("spanish_transcribe", "🇪🇸 Spanish");
        en.put("russian_transcribe", "🇷🇺 Russian");
        en.put("arabic_transcribe", "🇸🇦 Arabic");
        en.put("hindi_transcribe", "🇮🇳 Hindi");
        en.put("bengali_transcribe", "🇧🇩 Bengali");
        en.put("urdu_transcribe", "🇵🇰 Urdu");
        en.put("portuguese_transcribe", "🇵🇹 Portuguese");
        en.put("italian_transcribe", "🇮🇹 Italian");
        en.put("dutch_transcribe", "🇳🇱 Dutch");
        en.put("polish_transcribe", "🇵🇱 Polish");
        en.put("turkish_transcribe", "🇹🇷 Turkish");
        en.put("vietnamese_transcribe", "🇻🇳 Vietnamese");
        en.put("thai_transcribe", "🇹🇭 Thai");
        en.put("korean_transcribe", "🇰🇷 Korean");
        en.put("srt_format", "📄 SRT");
        en.put("ass_format", "🎨 ASS");
        en.put("import_complete", "Import Complete");
        en.put("import_success", "Media imported successfully.");
        en.put("enhancement_complete", "Enhancement Complete");
        en.put("enhancement_success", "Vocals extracted:");
        en.put("generation_complete", "Generation Complete");
        en.put("generation_success", "Captions saved:");
        en.put("download_complete", "Download Complete");
        en.put("download_success", "Model downloaded!");
        en.put("download_failed", "Download Failed");
        en.put("cancel_confirm", "Confirm Cancel");
        en.put("cancel_confirm_msg", "Cancel current operation?");
        en.put("force_cancel_confirm", "⚠️ Force cancel? This may cause instability.");
        en.put("no_audio", "No Audio");
        en.put("no_audio_msg", "No audio file loaded.");
        en.put("no_media", "No Media");
        en.put("no_media_msg", "Import media first.");
        en.put("overwrite", "Overwrite File?");
        en.put("overwrite_msg", "File exists:\n{}\nOverwrite?");
        en.put("login_required", "Please login with Google first.");
        en.put("conversion_warning", "Conversion Warning");
        en.put("conversion_warning_msg", "Using original file.");
        en.put("playback_error", "Playback Error");
        en.put("colab_timeout", "Colab Timeout");
        en.put("colab_timeout_msg", "No result file found.");
        en.put("network_error", "Network Error");
        en.put("model_load_error", "Model Load Error");
        en.put("settings_title", "Settings - Professional");
        en.put("general_tab", "General");
        en.put("paths_tab", "Paths");
        en.put("features_tab", "Features");
        en.put("advanced_tab", "Advanced");
        en.put("workspace_tab", "Workspace");
        en.put("presets_tab", "Presets");
        en.put("hardware_tab", "Hardware");
        en.put("visual_theme", "Theme");
        en.put("system_default", "System");
        en.put("light_mode", "Light");
        en.put("dark_mode", "Dark");
        en.put("ui_scaling", "UI Scale");
        en.put("scale_factor", "Scale:");
        en.put("temp_dir", "Temp Directory");
        en.put("temp_dir_placeholder", "System Temp");
        en.put("browse_folder", "Browse");
        en.put("models_dir", "Models Directory");
        en.put("models_dir_placeholder", "App Data");
        en.put("auto_features", "Auto Features");
        en.put("auto_enhance", "Auto-Enhance");
        en.put("default_language", "Default Language:");
        en.put("default_wpl", "Default Words/Line");
        en.put("words", "Words:");
        en.put("default_format", "Default Format");
        en.put("format", "Format:");
        en.put("cancel_options", "Cancel Options");
        en.put("confirm_cancel", "Confirm before cancel");
        en.put("force_cancel_timeout", "Force cancel after:");
        en.put("seconds", "s");
        en.put("max_retry", "Max retries:");
        en.put("ui_options", "UI Options");
        en.put("minimize_tray", "Minimize to tray");
        en.put("show_tooltips", "Show tooltips");
        en.put("ui_language", "Language:");
        en.put("apply_restart", "Apply & Restart");
        en.put("hardware_acceleration", "Hardware");
        en.put("cuda_available", "CUDA");
        en.put("cuda_not_available", "No CUDA");
        en.put("gpu_info", "GPU: {}");
        en.put("cpu_info", "CPU: {}");
        en.put("memory_info", "RAM: {:.1f} GB");
        en.put("using_gpu", "GPU Mode");
        en.put("using_cpu", "CPU Mode");
        en.put("gpu_temp", "GPU Temp: {}°C");
        en.put("gpu_usage", "GPU Usage: {}%");
        en.put("cpu_usage", "CPU Usage: {}%");
        en.put("gpu_memory", "GPU Memory: {:.1f}/{:.1f} GB");
        en.put("ram_usage", "RAM Usage: {:.1f}/{:.1f} GB ({:.0f}%)");
        en.put("disk_usage", "Disk Usage: {:.1f}/{:.1f} GB ({:.0f}%)");
        en.put("hardware_monitor", "Hardware Monitor");
        en.put("cpu_tab", "CPU");
        en.put("gpu_tab", "GPU");
        en.put("ram_tab", "RAM");
        en.put("disk_tab", "Disk");
        en.put("network_tab", "Network");
        en.put("performance_tab", "Performance");
        en.put("start_monitoring", "Start Monitoring");
        en.put("stop_monitoring", "Stop Monitoring");
        en.put("export_data", "Export Data");
        en.put("import_data", "Import Data");
        en.put("clear_history", "Clear History");
        en.put("refresh_rate", "Refresh Rate:");
        en.put("monitor_manager", "Monitor Manager");
        en.put("detect_monitors", "Detect Monitors");
        en.put("move_to_monitor", "Move to Monitor");
        en.put("create_window", "Create Window");
        en.put("close_window", "Close Window");
        en.put("monitor", "Monitor {}");
        en.put("primary", "Primary");
        en.put("resolution", "Resolution: {}x{}");
        en.put("refresh_rate", "Refresh Rate: {} Hz");
        en.put("workspace_customize", "Customize Workspace");
        en.put("accent_color", "Accent Color");
        en.put("glow_intensity", "Glow Intensity");
        en.put("animation_speed", "Animation Speed");
        en.put("card_opacity", "Card Opacity");
        en.put("font_family", "Font Family");
        en.put("font_size", "Font Size");
        en.put("reset_defaults", "Reset to Defaults");
        en.put("preview", "Preview");
        en.put("save_layout", "Save Layout");
        en.put("load_layout", "Load Layout");
        en.put("layout_name", "Layout Name:");
        en.put("select_layout", "Select Layout:");
        en.put("preset_name", "Preset Name:");
        en.put("apply_preset", "Apply Preset");
        en.put("save_preset", "Save Preset");
        en.put("delete_preset", "Delete Preset");
        en.put("animation_control", "Animation Control");
        en.put("enable_animations", "Enable Animations");
        en.put("animation_speed_slow", "Slow");
        en.put("animation_speed_normal", "Normal");
        en.put("animation_speed_fast", "Fast");

        ALL_TRANSLATIONS.put("en", en);

        // Japanese translations (simplified for brevity)
        Map<String, String> ja = new HashMap<>();
        ja.put("window_title", "NotyCaption Pro - プロフェッショナルAI字幕生成");
        ja.put("app_name", "NotyCaption Pro");
        ja.put("app_subtitle", "AI搭載字幕生成");
        ja.put("ready", "準備完了");
        ja.put("processing", "処理中...");
        ja.put("canceled", "キャンセル");
        ja.put("completed", "完了");
        ja.put("failed", "失敗");
        ja.put("edit_captions", "✏️ 字幕編集");
        ja.put("save_exit_edit", "💾 保存して終了");
        ja.put("settings", "⚙️ 設定");
        ja.put("download_model", "📥 モデルダウンロード");
        ja.put("login_google", "🔐 Googleログイン");
        ja.put("import_media", "📁 メディアインポート");
        ja.put("browse_output", "📂 出力先選択");
        ja.put("enhance_audio", "🎤 音声強調");
        ja.put("play_pause", "▶️ 再生 / ⏸️ 一時停止");
        ja.put("playing", "⏸️ 再生中...");
        ja.put("paused", "▶️ 再生 / ⏸️ 一時停止");
        ja.put("generate", "🚀 字幕生成");
        ja.put("cancel", "キャンセル");
        ja.put("force_cancel", "⚠️ 強制キャンセル");
        ja.put("reopen_notebook", "🔗 ノートブックを開く");
        ja.put("copy_url", "📋 URLをコピー");
        ja.put("workspace", "🎨 ワークスペース");
        ja.put("save_layout", "💾 レイアウト保存");
        ja.put("load_layout", "📂 レイアウト読み込み");
        ja.put("presets", "🎨 プリセット");
        ja.put("hardware", "🖥️ ハードウェア");
        ja.put("monitor", "📊 モニター");
        ja.put("performance", "📈 パフォーマンス");
        ja.put("export", "📤 エクスポート");
        ja.put("import", "📥 インポート");
        ja.put("preview", "👁️ プレビュー");
        ja.put("refresh", "🔄 更新");
        ja.put("ai_caption_editor", "AI字幕エディター");
        ja.put("processing_mode", "モード：");
        ja.put("language", "言語：");
        ja.put("words_per_line", "1行あたりの単語数：");
        ja.put("output_format", "フォーマット：");
        ja.put("output_folder", "出力フォルダ：");
        ja.put("status", "ステータス：");
        ja.put("notebook_url", "ノートブックURL：");
        ja.put("not_available", "利用不可");
        ja.put("idle", "待機中");
        ja.put("speed", "速度：");
        ja.put("eta", "残り時間：");
        ja.put("downloading", "ダウンロード中...");
        ja.put("uploading", "アップロード中...");
        ja.put("waiting", "待機中...");
        ja.put("colab_link", "Colabリンク：");
        ja.put("click_to_open", "クリックして開く");
        ja.put("normal_mode", "🖥️ ローカル");
        ja.put("online_mode", "☁️ オンライン");
        ja.put("english_transcribe", "🇺🇸 英語");
        ja.put("japanese_translate", "🇯🇵 日本語 → 英語");
        ja.put("chinese_transcribe", "🇨🇳 中国語");
        ja.put("french_transcribe", "🇫🇷 フランス語");
        ja.put("german_transcribe", "🇩🇪 ドイツ語");
        ja.put("spanish_transcribe", "🇪🇸 スペイン語");
        ja.put("russian_transcribe", "🇷🇺 ロシア語");
        ja.put("arabic_transcribe", "🇸🇦 アラビア語");
        ja.put("hindi_transcribe", "🇮🇳 ヒンディー語");
        ja.put("bengali_transcribe", "🇧🇩 ベンガル語");
        ja.put("urdu_transcribe", "🇵🇰 ウルドゥー語");
        ja.put("portuguese_transcribe", "🇵🇹 ポルトガル語");
        ja.put("italian_transcribe", "🇮🇹 イタリア語");
        ja.put("dutch_transcribe", "🇳🇱 オランダ語");
        ja.put("polish_transcribe", "🇵🇱 ポーランド語");
        ja.put("turkish_transcribe", "🇹🇷 トルコ語");
        ja.put("vietnamese_transcribe", "🇻🇳 ベトナム語");
        ja.put("thai_transcribe", "🇹🇭 タイ語");
        ja.put("korean_transcribe", "🇰🇷 韓国語");
        ja.put("srt_format", "📄 SRT");
        ja.put("ass_format", "🎨 ASS");
        ALL_TRANSLATIONS.put("ja", ja);

        // Russian translations
        Map<String, String> ru = new HashMap<>();
        ru.put("window_title", "NotyCaption Pro - Профессиональный генератор субтитров с ИИ");
        ru.put("app_name", "NotyCaption Pro");
        ru.put("app_subtitle", "Генератор субтитров с ИИ");
        ru.put("ready", "Готово");
        ru.put("processing", "Обработка...");
        ru.put("canceled", "Отменено");
        ru.put("completed", "Завершено");
        ru.put("failed", "Ошибка");
        ru.put("edit_captions", "✏️ Редактировать");
        ru.put("save_exit_edit", "💾 Сохранить и выйти");
        ru.put("settings", "⚙️ Настройки");
        ru.put("download_model", "📥 Скачать модель");
        ru.put("login_google", "🔐 Войти через Google");
        ru.put("import_media", "📁 Импорт медиа");
        ru.put("browse_output", "📂 Выбрать папку");
        ru.put("enhance_audio", "🎤 Улучшить аудио");
        ru.put("play_pause", "▶️ Воспроизвести / ⏸️ Пауза");
        ru.put("playing", "⏸️ Воспроизведение...");
        ru.put("paused", "▶️ Воспроизвести / ⏸️ Пауза");
        ru.put("generate", "🚀 Создать субтитры");
        ru.put("cancel", "Отменить");
        ru.put("force_cancel", "⚠️ Принудительно");
        ru.put("reopen_notebook", "🔗 Открыть блокнот");
        ru.put("copy_url", "📋 Копировать URL");
        ru.put("workspace", "🎨 Рабочее пространство");
        ru.put("save_layout", "💾 Сохранить макет");
        ru.put("load_layout", "📂 Загрузить макет");
        ru.put("presets", "🎨 Пресеты");
        ru.put("hardware", "🖥️ Оборудование");
        ru.put("monitor", "📊 Монитор");
        ru.put("performance", "📈 Производительность");
        ru.put("export", "📤 Экспорт");
        ru.put("import", "📥 Импорт");
        ru.put("preview", "👁️ Предпросмотр");
        ru.put("refresh", "🔄 Обновить");
        ru.put("ai_caption_editor", "Редактор субтитров с ИИ");
        ru.put("processing_mode", "Режим:");
        ru.put("language", "Язык:");
        ru.put("words_per_line", "Слов в строке:");
        ru.put("output_format", "Формат:");
        ru.put("output_folder", "Папка вывода:");
        ru.put("status", "Статус:");
        ru.put("notebook_url", "URL блокнота:");
        ru.put("not_available", "Недоступно");
        ru.put("idle", "Ожидание");
        ru.put("speed", "Скорость:");
        ru.put("eta", "Осталось:");
        ru.put("downloading", "Загрузка...");
        ru.put("uploading", "Выгрузка...");
        ru.put("waiting", "Ожидание...");
        ru.put("colab_link", "Ссылка Colab:");
        ru.put("click_to_open", "Нажмите для открытия");
        ru.put("normal_mode", "🖥️ Локальный");
        ru.put("online_mode", "☁️ Онлайн");
        ru.put("english_transcribe", "🇺🇸 Английский");
        ru.put("japanese_translate", "🇯🇵 Японский → Английский");
        ru.put("chinese_transcribe", "🇨🇳 Китайский");
        ru.put("french_transcribe", "🇫🇷 Французский");
        ru.put("german_transcribe", "🇩🇪 Немецкий");
        ru.put("spanish_transcribe", "🇪🇸 Испанский");
        ru.put("russian_transcribe", "🇷🇺 Русский");
        ru.put("arabic_transcribe", "🇸🇦 Арабский");
        ru.put("hindi_transcribe", "🇮🇳 Хинди");
        ru.put("bengali_transcribe", "🇧🇩 Бенгальский");
        ru.put("urdu_transcribe", "🇵🇰 Урду");
        ru.put("portuguese_transcribe", "🇵🇹 Португальский");
        ru.put("italian_transcribe", "🇮🇹 Итальянский");
        ru.put("dutch_transcribe", "🇳🇱 Нидерландский");
        ru.put("polish_transcribe", "🇵🇱 Польский");
        ru.put("turkish_transcribe", "🇹🇷 Турецкий");
        ru.put("vietnamese_transcribe", "🇻🇳 Вьетнамский");
        ru.put("thai_transcribe", "🇹🇭 Тайский");
        ru.put("korean_transcribe", "🇰🇷 Корейский");
        ru.put("srt_format", "📄 SRT");
        ru.put("ass_format", "🎨 ASS");
        ALL_TRANSLATIONS.put("ru", ru);

        // German translations
        Map<String, String> de = new HashMap<>();
        de.put("window_title", "NotyCaption Pro - Professioneller KI-Untertitelgenerator");
        de.put("app_name", "NotyCaption Pro");
        de.put("app_subtitle", "KI-gestützter Untertitelgenerator");
        de.put("ready", "Bereit");
        de.put("processing", "Verarbeitung...");
        de.put("canceled", "Abgebrochen");
        de.put("completed", "Abgeschlossen");
        de.put("failed", "Fehlgeschlagen");
        de.put("edit_captions", "✏️ Untertitel bearbeiten");
        de.put("save_exit_edit", "💾 Speichern & Beenden");
        de.put("settings", "⚙️ Einstellungen");
        de.put("download_model", "📥 Modell herunterladen");
        de.put("login_google", "🔐 Google-Anmeldung");
        de.put("import_media", "📁 Medien importieren");
        de.put("browse_output", "📂 Ausgabeordner");
        de.put("enhance_audio", "🎤 Audio verbessern");
        de.put("play_pause", "▶️ Abspielen / ⏸️ Pause");
        de.put("playing", "⏸️ Wiedergabe...");
        de.put("paused", "▶️ Abspielen / ⏸️ Pause");
        de.put("generate", "🚀 Untertitel generieren");
        de.put("cancel", "Abbrechen");
        de.put("force_cancel", "⚠️ Erzwingen");
        de.put("reopen_notebook", "🔗 Notizbuch öffnen");
        de.put("copy_url", "📋 URL kopieren");
        de.put("workspace", "🎨 Arbeitsbereich");
        de.put("save_layout", "💾 Layout speichern");
        de.put("load_layout", "📂 Layout laden");
        de.put("presets", "🎨 Voreinstellungen");
        de.put("hardware", "🖥️ Hardware");
        de.put("monitor", "📊 Monitor");
        de.put("performance", "📈 Leistung");
        de.put("export", "📤 Exportieren");
        de.put("import", "📥 Importieren");
        de.put("preview", "👁️ Vorschau");
        de.put("refresh", "🔄 Aktualisieren");
        de.put("ai_caption_editor", "KI-Untertitel-Editor");
        de.put("processing_mode", "Modus:");
        de.put("language", "Sprache:");
        de.put("words_per_line", "Wörter pro Zeile:");
        de.put("output_format", "Format:");
        de.put("output_folder", "Ausgabeordner:");
        de.put("status", "Status:");
        de.put("notebook_url", "Notizbuch-URL:");
        de.put("not_available", "Nicht verfügbar");
        de.put("idle", "Bereit");
        de.put("speed", "Geschwindigkeit:");
        de.put("eta", "Verbleibend:");
        de.put("downloading", "Herunterladen...");
        de.put("uploading", "Hochladen...");
        de.put("waiting", "Warten...");
        de.put("colab_link", "Colab-Link:");
        de.put("click_to_open", "Klicken zum Öffnen");
        de.put("normal_mode", "🖥️ Lokal");
        de.put("online_mode", "☁️ Online");
        de.put("english_transcribe", "🇺🇸 Englisch");
        de.put("japanese_translate", "🇯🇵 Japanisch → Englisch");
        de.put("chinese_transcribe", "🇨🇳 Chinesisch");
        de.put("french_transcribe", "🇫🇷 Französisch");
        de.put("german_transcribe", "🇩🇪 Deutsch");
        de.put("spanish_transcribe", "🇪🇸 Spanisch");
        de.put("russian_transcribe", "🇷🇺 Russisch");
        de.put("arabic_transcribe", "🇸🇦 Arabisch");
        de.put("hindi_transcribe", "🇮🇳 Hindi");
        de.put("bengali_transcribe", "🇧🇩 Bengalisch");
        de.put("urdu_transcribe", "🇵🇰 Urdu");
        de.put("portuguese_transcribe", "🇵🇹 Portugiesisch");
        de.put("italian_transcribe", "🇮🇹 Italienisch");
        de.put("dutch_transcribe", "🇳🇱 Niederländisch");
        de.put("polish_transcribe", "🇵🇱 Polnisch");
        de.put("turkish_transcribe", "🇹🇷 Türkisch");
        de.put("vietnamese_transcribe", "🇻🇳 Vietnamesisch");
        de.put("thai_transcribe", "🇹🇭 Thailändisch");
        de.put("korean_transcribe", "🇰🇷 Koreanisch");
        de.put("srt_format", "📄 SRT");
        de.put("ass_format", "🎨 ASS");
        ALL_TRANSLATIONS.put("de", de);

        // Hindi translations
        Map<String, String> hi = new HashMap<>();
        hi.put("window_title", "NotyCaption Pro - पेशेवर AI कैप्शन जनरेटर");
        hi.put("app_name", "NotyCaption Pro");
        hi.put("app_subtitle", "AI-संचालित कैप्शन जनरेटर");
        hi.put("ready", "तैयार");
        hi.put("processing", "प्रक्रियाधीन...");
        hi.put("canceled", "रद्द");
        hi.put("completed", "पूर्ण");
        hi.put("failed", "विफल");
        hi.put("edit_captions", "✏️ कैप्शन संपादित करें");
        hi.put("save_exit_edit", "💾 सहेजें और बाहर निकलें");
        hi.put("settings", "⚙️ सेटिंग्स");
        hi.put("download_model", "📥 मॉडल डाउनलोड करें");
        hi.put("login_google", "🔐 Google लॉगिन");
        hi.put("import_media", "📁 मीडिया आयात करें");
        hi.put("browse_output", "📂 आउटपुट फ़ोल्डर");
        hi.put("enhance_audio", "🎤 ऑडियो बढ़ाएं");
        hi.put("play_pause", "▶️ चलाएं / ⏸️ रोकें");
        hi.put("playing", "⏸️ चल रहा है...");
        hi.put("paused", "▶️ चलाएं / ⏸️ रोकें");
        hi.put("generate", "🚀 कैप्शन जनरेट करें");
        hi.put("cancel", "रद्द करें");
        hi.put("force_cancel", "⚠️ जबरन रद्द करें");
        hi.put("reopen_notebook", "🔗 नोटबुक खोलें");
        hi.put("copy_url", "📋 URL कॉपी करें");
        hi.put("workspace", "🎨 कार्यक्षेत्र");
        hi.put("save_layout", "💾 लेआउट सहेजें");
        hi.put("load_layout", "📂 लेआउट लोड करें");
        hi.put("presets", "🎨 प्रीसेट");
        hi.put("hardware", "🖥️ हार्डवेयर");
        hi.put("monitor", "📊 मॉनिटर");
        hi.put("performance", "📈 प्रदर्शन");
        hi.put("export", "📤 निर्यात");
        hi.put("import", "📥 आयात");
        hi.put("preview", "👁️ पूर्वावलोकन");
        hi.put("refresh", "🔄 ताज़ा करें");
        hi.put("ai_caption_editor", "AI कैप्शन संपादक");
        hi.put("processing_mode", "मोड:");
        hi.put("language", "भाषा:");
        hi.put("words_per_line", "प्रति पंक्ति शब्द:");
        hi.put("output_format", "फॉर्मेट:");
        hi.put("output_folder", "आउटपुट फ़ोल्डर:");
        hi.put("status", "स्थिति:");
        hi.put("notebook_url", "नोटबुक URL:");
        hi.put("not_available", "उपलब्ध नहीं");
        hi.put("idle", "निष्क्रिय");
        hi.put("speed", "गति:");
        hi.put("eta", "शेष समय:");
        hi.put("downloading", "डाउनलोड हो रहा है...");
        hi.put("uploading", "अपलोड हो रहा है...");
        hi.put("waiting", "प्रतीक्षा कर रहा है...");
        hi.put("colab_link", "Colab लिंक:");
        hi.put("click_to_open", "खोलने के लिए क्लिक करें");
        hi.put("normal_mode", "🖥️ स्थानीय");
        hi.put("online_mode", "☁️ ऑनलाइन");
        hi.put("english_transcribe", "🇺🇸 अंग्रेजी");
        hi.put("japanese_translate", "🇯🇵 जापानी → अंग्रेजी");
        hi.put("chinese_transcribe", "🇨🇳 चीनी");
        hi.put("french_transcribe", "🇫🇷 फ्रेंच");
        hi.put("german_transcribe", "🇩🇪 जर्मन");
        hi.put("spanish_transcribe", "🇪🇸 स्पेनिश");
        hi.put("russian_transcribe", "🇷🇺 रूसी");
        hi.put("arabic_transcribe", "🇸🇦 अरबी");
        hi.put("hindi_transcribe", "🇮🇳 हिंदी");
        hi.put("bengali_transcribe", "🇧🇩 बंगाली");
        hi.put("urdu_transcribe", "🇵🇰 उर्दू");
        hi.put("portuguese_transcribe", "🇵🇹 पुर्तगाली");
        hi.put("italian_transcribe", "🇮🇹 इतालवी");
        hi.put("dutch_transcribe", "🇳🇱 डच");
        hi.put("polish_transcribe", "🇵🇱 पोलिश");
        hi.put("turkish_transcribe", "🇹🇷 तुर्की");
        hi.put("vietnamese_transcribe", "🇻🇳 वियतनामी");
        hi.put("thai_transcribe", "🇹🇭 थाई");
        hi.put("korean_transcribe", "🇰🇷 कोरियाई");
        hi.put("srt_format", "📄 SRT");
        hi.put("ass_format", "🎨 ASS");
        ALL_TRANSLATIONS.put("hi", hi);

        // Urdu translations
        Map<String, String> ur = new HashMap<>();
        ur.put("window_title", "NotyCaption Pro - پیشہ ور AI کیپشن جنریٹر");
        ur.put("app_name", "NotyCaption Pro");
        ur.put("app_subtitle", "AI سے چلنے والا کیپشن جنریٹر");
        ur.put("ready", "تیار");
        ur.put("processing", "پروسیسنگ...");
        ur.put("canceled", "منسوخ");
        ur.put("completed", "مکمل");
        ur.put("failed", "ناکام");
        ur.put("edit_captions", "✏️ کیپشن میں ترمیم");
        ur.put("save_exit_edit", "💾 محفوظ کریں اور باہر نکلیں");
        ur.put("settings", "⚙️ ترتیبات");
        ur.put("download_model", "📥 ماڈل ڈاؤن لوڈ");
        ur.put("login_google", "🔐 Google لاگ ان");
        ur.put("import_media", "📁 میڈیا درآمد");
        ur.put("browse_output", "📂 آؤٹ پٹ فولڈر");
        ur.put("enhance_audio", "🎤 آڈیو بہتر کریں");
        ur.put("play_pause", "▶️ چلائیں / ⏸️ روکیں");
        ur.put("playing", "⏸️ چل رہا ہے...");
        ur.put("paused", "▶️ چلائیں / ⏸️ روکیں");
        ur.put("generate", "🚀 کیپشن تیار کریں");
        ur.put("cancel", "منسوخ کریں");
        ur.put("force_cancel", "⚠️ زبردستی منسوخ کریں");
        ur.put("reopen_notebook", "🔗 نوٹ بک کھولیں");
        ur.put("copy_url", "📋 URL کاپی کریں");
        ur.put("workspace", "🎨 کام کی جگہ");
        ur.put("save_layout", "💾 لے آؤٹ محفوظ کریں");
        ur.put("load_layout", "📂 لے آؤٹ لوڈ کریں");
        ur.put("presets", "🎨 پری سیٹس");
        ur.put("hardware", "🖥️ ہارڈویئر");
        ur.put("monitor", "📊 مانیٹر");
        ur.put("performance", "📈 کارکردگی");
        ur.put("export", "📤 برآمد");
        ur.put("import", "📥 درآمد");
        ur.put("preview", "👁️ پیش نظارہ");
        ur.put("refresh", "🔄 تازہ کریں");
        ur.put("ai_caption_editor", "AI کیپشن ایڈیٹر");
        ur.put("processing_mode", "موڈ:");
        ur.put("language", "زبان:");
        ur.put("words_per_line", "الفاظ فی سطر:");
        ur.put("output_format", "فارمیٹ:");
        ur.put("output_folder", "آؤٹ پٹ فولڈر:");
        ur.put("status", "حالت:");
        ur.put("notebook_url", "نوٹ بک URL:");
        ur.put("not_available", "دستیاب نہیں");
        ur.put("idle", "غیر فعال");
        ur.put("speed", "رفتار:");
        ur.put("eta", "باقی وقت:");
        ur.put("downloading", "ڈاؤن لوڈ ہو رہا ہے...");
        ur.put("uploading", "اپ لوڈ ہو رہا ہے...");
        ur.put("waiting", "انتظار...");
        ur.put("colab_link", "Colab لنک:");
        ur.put("click_to_open", "کھولنے کے لیے کلک کریں");
        ur.put("normal_mode", "🖥️ مقامی");
        ur.put("online_mode", "☁️ آن لائن");
        ur.put("english_transcribe", "🇺🇸 انگریزی");
        ur.put("japanese_translate", "🇯🇵 جاپانی → انگریزی");
        ur.put("chinese_transcribe", "🇨🇳 چینی");
        ur.put("french_transcribe", "🇫🇷 فرانسیسی");
        ur.put("german_transcribe", "🇩🇪 جرمن");
        ur.put("spanish_transcribe", "🇪🇸 ہسپانوی");
        ur.put("russian_transcribe", "🇷🇺 روسی");
        ur.put("arabic_transcribe", "🇸🇦 عربی");
        ur.put("hindi_transcribe", "🇮🇳 ہندی");
        ur.put("bengali_transcribe", "🇧🇩 بنگالی");
        ur.put("urdu_transcribe", "🇵🇰 اردو");
        ur.put("portuguese_transcribe", "🇵🇹 پرتگالی");
        ur.put("italian_transcribe", "🇮🇹 اطالوی");
        ur.put("dutch_transcribe", "🇳🇱 ڈچ");
        ur.put("polish_transcribe", "🇵🇱 پولش");
        ur.put("turkish_transcribe", "🇹🇷 ترکی");
        ur.put("vietnamese_transcribe", "🇻🇳 ویتنامی");
        ur.put("thai_transcribe", "🇹🇭 تھائی");
        ur.put("korean_transcribe", "🇰🇷 کورین");
        ur.put("srt_format", "📄 SRT");
        ur.put("ass_format", "🎨 ASS");
        ALL_TRANSLATIONS.put("ur", ur);

        // Arabic translations
        Map<String, String> ar = new HashMap<>();
        ar.put("window_title", "NotyCaption Pro - مولد التسميات التوضيحية بالذكاء الاصطناعي المحترف");
        ar.put("app_name", "NotyCaption Pro");
        ar.put("app_subtitle", "مولد التسميات التوضيحية بالذكاء الاصطناعي");
        ar.put("ready", "جاهز");
        ar.put("processing", "جاري المعالجة...");
        ar.put("canceled", "ملغي");
        ar.put("completed", "مكتمل");
        ar.put("failed", "فشل");
        ar.put("edit_captions", "✏️ تحرير التسميات");
        ar.put("save_exit_edit", "💾 حفظ وخروج");
        ar.put("settings", "⚙️ الإعدادات");
        ar.put("download_model", "📥 تحميل النموذج");
        ar.put("login_google", "🔐 تسجيل الدخول Google");
        ar.put("import_media", "📁 استيراد وسائط");
        ar.put("browse_output", "📂 مجلد الإخراج");
        ar.put("enhance_audio", "🎤 تحسين الصوت");
        ar.put("play_pause", "▶️ تشغيل / ⏸️ إيقاف مؤقت");
        ar.put("playing", "⏸️ جار التشغيل...");
        ar.put("paused", "▶️ تشغيل / ⏸️ إيقاف مؤقت");
        ar.put("generate", "🚀 إنشاء التسميات");
        ar.put("cancel", "إلغاء");
        ar.put("force_cancel", "⚠️ إلغاء强制");
        ar.put("reopen_notebook", "🔗 فتح الدفتر");
        ar.put("copy_url", "📋 نسخ الرابط");
        ar.put("workspace", "🎨 مساحة العمل");
        ar.put("save_layout", "💾 حفظ التخطيط");
        ar.put("load_layout", "📂 تحميل التخطيط");
        ar.put("presets", "🎨 الإعدادات المسبقة");
        ar.put("hardware", "🖥️ الأجهزة");
        ar.put("monitor", "📊 مراقب");
        ar.put("performance", "📈 الأداء");
        ar.put("export", "📤 تصدير");
        ar.put("import", "📥 استيراد");
        ar.put("preview", "👁️ معاينة");
        ar.put("refresh", "🔄 تحديث");
        ar.put("ai_caption_editor", "محرر التسميات بالذكاء الاصطناعي");
        ar.put("processing_mode", "الوضع:");
        ar.put("language", "اللغة:");
        ar.put("words_per_line", "الكلمات في السطر:");
        ar.put("output_format", "التنسيق:");
        ar.put("output_folder", "مجلد الإخراج:");
        ar.put("status", "الحالة:");
        ar.put("notebook_url", "رابط الدفتر:");
        ar.put("not_available", "غير متاح");
        ar.put("idle", "خامل");
        ar.put("speed", "السرعة:");
        ar.put("eta", "الوقت المتبقي:");
        ar.put("downloading", "جاري التحميل...");
        ar.put("uploading", "جاري الرفع...");
        ar.put("waiting", "انتظار...");
        ar.put("colab_link", "رابط Colab:");
        ar.put("click_to_open", "انقر للفتح");
        ar.put("normal_mode", "🖥️ محلي");
        ar.put("online_mode", "☁️ عبر الإنترنت");
        ar.put("english_transcribe", "🇺🇸 الإنجليزية");
        ar.put("japanese_translate", "🇯🇵 اليابانية → الإنجليزية");
        ar.put("chinese_transcribe", "🇨🇳 الصينية");
        ar.put("french_transcribe", "🇫🇷 الفرنسية");
        ar.put("german_transcribe", "🇩🇪 الألمانية");
        ar.put("spanish_transcribe", "🇪🇸 الإسبانية");
        ar.put("russian_transcribe", "🇷🇺 الروسية");
        ar.put("arabic_transcribe", "🇸🇦 العربية");
        ar.put("hindi_transcribe", "🇮🇳 الهندية");
        ar.put("bengali_transcribe", "🇧🇩 البنغالية");
        ar.put("urdu_transcribe", "🇵🇰 الأردية");
        ar.put("portuguese_transcribe", "🇵🇹 البرتغالية");
        ar.put("italian_transcribe", "🇮🇹 الإيطالية");
        ar.put("dutch_transcribe", "🇳🇱 الهولندية");
        ar.put("polish_transcribe", "🇵🇱 البولندية");
        ar.put("turkish_transcribe", "🇹🇷 التركية");
        ar.put("vietnamese_transcribe", "🇻🇳 الفيتنامية");
        ar.put("thai_transcribe", "🇹🇭 التايلاندية");
        ar.put("korean_transcribe", "🇰🇷 الكورية");
        ar.put("srt_format", "📄 SRT");
        ar.put("ass_format", "🎨 ASS");
        ALL_TRANSLATIONS.put("ar", ar);
    }

    public Translator(String language) {
        this.language = language;
        this.translations = ALL_TRANSLATIONS.getOrDefault(language, ALL_TRANSLATIONS.get("en"));
    }

    public String tr(String key) {
        return translations.getOrDefault(key, key);
    }

    public String tr(String key, Object... args) {
        String template = translations.getOrDefault(key, key);
        return String.format(template, args);
    }

    public void setLanguage(String language) {
        this.language = language;
        this.translations = ALL_TRANSLATIONS.getOrDefault(language, ALL_TRANSLATIONS.get("en"));
    }

    public String getLanguage() {
        return language;
    }
}